version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - ci_network
    user: root

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
      - "9092"
      # - "9092:9092"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_conf:/opt/sonarqube/conf
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - ci_network

  nexus:
    image: sonatype/nexus3
    environment:
        # - JAVA_OPTS="-Dorg.eclipse.jetty.server.Request.maxFormContentSize=50MB"
        - JAVA_OPTS="-Dorg.eclipse.jetty.server.Request.maxFormContentSize=52428800"  # Set to 50MB
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - ci_network
    # command: ["-n", "65536"] 

networks:
  ci_network:
    driver: bridge

volumes:
  jenkins_home:
  nexus_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_conf: